import React from 'react';

export const Dashboard = () => {
  return (
    <>
      <div>
        Dashboard 1
      </div>
      <div>
        Dashboard 2
      </div>
      <div>
        Dashboard 3
      </div>
      <div>
        Dashboard 4
      </div>
      <div>
        Dashboard 5
      </div>
      <div>
        Dashboard 6
      </div>
      <div>
        Dashboard 7
      </div>
      <div>
        Dashboard 8
      </div>
      <div>
        Dashboard 9
      </div>
      <div>
        Dashboard 10
      </div>
      <div>
        Dashboard 11
      </div>
      <div>
        Dashboard 12
      </div>
      <div>
        Dashboard 13
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>
      <div>
        Dashboard
      </div>

    </>
  );
};